/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dc.kafka.avro.audio;
@org.apache.avro.specific.AvroGenerated
public enum Action implements org.apache.avro.generic.GenericEnumSymbol<Action> {
  PLAY, STOP, PAUSE, RESUME  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Action\",\"namespace\":\"com.dc.kafka.avro.audio\",\"symbols\":[\"PLAY\",\"STOP\",\"PAUSE\",\"RESUME\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
